### ISSUE TITLE
Redundancy of cross-links in the <Peptide> element

### ISSUE THREAD

**Issue by mhoopmann** [HUPO-PSI/mzIdentML#100]
I have a few questions with mzIdentML 1.2 and cross-linking implementation. I have also been using the validator to try to understand what is going on when implementing 1.2 on cross-linked database search results generated in-house.

I have collected multiple spectra for the sample precursor ion, and the search results present the same cross-linked pair of peptides as a PSM. In other words: multiple spectra with identical results. For each of these SpectrumIdentificationResult, I have two SpectrumIdentificationItem with a cvParam "accession" of MS:1002511 and a "value" with the unique identifier for the cross-link (donor and acceptor) in my Peptide element.

When I have 3 or more of these spectra with identical PSMs, the validator says I'm using the value of my cvParam in the SpectrumIdentificationItem too many times. It appears that the validator doesn't like that I'm using the same Peptide elements with more than one SpectrumIdentificationResult when specifically referring to cross-linked peptides.

So my questions are:
1. Does this mean that all cross-linked peptides must be listed redundantly in the Peptide elements?

2. Does this mean the unique "value" in the cvParam of the Modification element for the cross-linked site of these redundant Peptides elements is simply to circumvent the definition of a Peptide Element (which explicitly forbids redundancy) as presented in chapter 6.48 of the mzIdentML schema?

3. Or is this a bug in the validator?

4. And should the validator be able to identify these redundancies when they happen in only 2 spectra? (I am assuming that the validator assumes these particular cases are isotope labelled cross-linkers, which they are definitely not in my results).

5. Probably a question for a different topic, but is all this redundancy necessary? For example, it appears I have to list the same peptide sequence, with the same modifications, multiple times for every partner peptide it may be linked to. Worse still, its status of donor or acceptor can alternate based on its partner peptide: but this has no bearing on any chemical significance, and is merely an artifact of sequence string length. And thus the sequence is again(!!) redundant in the Peptide element list for simply flipping the cvParam on the same Modification.

Any clarity here would be greatly appreciated. Perhaps I'm just misunderstanding something very basic.

Thanks,
Mike

**Comment by andrewrobertjones** [comment]
To me this sounds like a bug in the validator, can you post an example mzid file for us to take a look at

**Comment by mhoopmann** [comment]
Sure thing: https://regis-web.systemsbiology.net/PublicDatasets/mikeh/mzID/test.mzid

Please note that our in-house implementation is still a work-in-progress for cross-linking. That being said, the redundancy issue is quite apparent.

Thanks much!

**Comment by germa** [comment]
Dear Mike,

Sorry for the late reply.
In general we want to avoid redundancy in mzIdentML whenever possible.
Therefore also cross-linked peptides should only be listed once in the <Peptide> elements.

1. For example in the following I listed all SpectrumIdentificationItems with value=”2301” for the cvParam MS:1002511.
The first two reference the peptides "Pep5238" and "Pep5237", which again have for the cvParams MS:1002509 and MS:1002510 the correct value=”2301”.

2. But the next two SpectrumIdentificationItems with value=”2301” for the cvParam MS:1002511 reference the peptides "Pep5176" and "Pep5175", which have another value=”2271” for their cvParams MS:1002509 and MS:1002510.

3. The last two SpectrumIdentificationItems with value=”2301” for the cvParam MS:1002511 reference the peptides "Pep5027" and "Pep5028", which have another value=”2201” for their cvParams MS:1002509 and MS:1002510.

So I think the problem is that the values are not correctly matched for the cases 2 and 3.

<SpectrumIdentificationResult id="SF0_4830" spectrumID="scan=24612" spectraData_ref="SF0">
    <SpectrumIdentificationItem id="SF0_4830_0" chargeState="3" experimentalMassToCharge="1250.575683" rank="1" passThreshold="true" calculatedMassToCharge="1250.591047" peptide_ref="Pep5238">
      <PeptideEvidenceRef peptideEvidence_ref="PE5683"/>
      <cvParam accession="MS:1002511" name="cross-link spectrum identification item" cvRef="PSI-MS" value="2301"/>
      <userParam name="Kojak:kojak_score" value="0.705000"/>
      <userParam name="Kojak:delta_score" value="0.010000"/>
      <userParam name="Kojak:ppm_error" value="12.294900"/>
      <userParam name="Kojak:e-value" value="12.820000"/>
      <userParam name="Kojak:ion_match" value="7"/>
      <userParam name="Kojak:consecutive_ion_match" value="1"/>
    </SpectrumIdentificationItem>
    <SpectrumIdentificationItem id="SF0_4830_1" chargeState="3" experimentalMassToCharge="1250.575683" rank="1" passThreshold="true" calculatedMassToCharge="1250.591047" peptide_ref="Pep5237">
      <PeptideEvidenceRef peptideEvidence_ref="PE5684"/>
      <cvParam accession="MS:1002511" name="cross-link spectrum identification item" cvRef="PSI-MS" value="2301"/>
      <userParam name="Kojak:kojak_score" value="0.705000"/>
      <userParam name="Kojak:delta_score" value="0.010000"/>
      <userParam name="Kojak:ppm_error" value="12.294900"/>
      <userParam name="Kojak:e-value" value="12.820000"/>
      <userParam name="Kojak:ion_match" value="7"/>
      <userParam name="Kojak:consecutive_ion_match" value="1"/>
    </SpectrumIdentificationItem>
    <cvParam accession="MS:1000894" name="retention time" cvRef="PSI-MS" unitAccession="UO:0000010" unitCvRef="UO" unitName="second" value="68.7000"/>
</SpectrumIdentificationResult>

	 
<SpectrumIdentificationResult id="SF0_4831" spectrumID="scan=24614" spectraData_ref="SF0">
    <SpectrumIdentificationItem id="SF0_4831_0" chargeState="4" experimentalMassToCharge="547.549679" rank="1" passThreshold="true" calculatedMassToCharge="547.549633" peptide_ref="Pep5176">
      <PeptideEvidenceRef peptideEvidence_ref="PE5617"/>
      <cvParam accession="MS:1002511" name="cross-link spectrum identification item" cvRef="PSI-MS" value="2301"/>
      <userParam name="Kojak:kojak_score" value="1.930000"/>
      <userParam name="Kojak:delta_score" value="0.060000"/>
      <userParam name="Kojak:ppm_error" value="-8.57E-002"/>
      <userParam name="Kojak:e-value" value="0.059090"/>
      <userParam name="Kojak:ion_match" value="14"/>
      <userParam name="Kojak:consecutive_ion_match" value="3"/>
    </SpectrumIdentificationItem>
    <SpectrumIdentificationItem id="SF0_4831_1" chargeState="4" experimentalMassToCharge="547.549679" rank="1" passThreshold="true" calculatedMassToCharge="547.549633" peptide_ref="Pep5175">
      <PeptideEvidenceRef peptideEvidence_ref="PE5618"/>
      <cvParam accession="MS:1002511" name="cross-link spectrum identification item" cvRef="PSI-MS" value="2301"/>
      <userParam name="Kojak:kojak_score" value="1.930000"/>
      <userParam name="Kojak:delta_score" value="0.060000"/>
      <userParam name="Kojak:ppm_error" value="-8.57E-002"/>
      <userParam name="Kojak:e-value" value="0.059090"/>
      <userParam name="Kojak:ion_match" value="14"/>
      <userParam name="Kojak:consecutive_ion_match" value="3"/>
    </SpectrumIdentificationItem>
    <cvParam accession="MS:1000894" name="retention time" cvRef="PSI-MS" unitAccession="UO:0000010" unitCvRef="UO" unitName="second" value="68.7000"/>
</SpectrumIdentificationResult>

<SpectrumIdentificationResult id="SF0_4832" spectrumID="scan=24615" spectraData_ref="SF0">
    <SpectrumIdentificationItem id="SF0_4832_0" chargeState="4" experimentalMassToCharge="1007.708591" rank="1" passThreshold="true" calculatedMassToCharge="1007.700997" peptide_ref="Pep5027">
      <PeptideEvidenceRef peptideEvidence_ref="PE5453"/>
      <cvParam accession="MS:1002511" name="cross-link spectrum identification item" cvRef="PSI-MS" value="2301"/>
      <userParam name="Kojak:kojak_score" value="1.010000"/>
      <userParam name="Kojak:delta_score" value="0.345000"/>
      <userParam name="Kojak:ppm_error" value="-7.54E+000"/>
      <userParam name="Kojak:e-value" value="3.738000"/>
      <userParam name="Kojak:ion_match" value="9"/>
      <userParam name="Kojak:consecutive_ion_match" value="1"/>
    </SpectrumIdentificationItem>
    <SpectrumIdentificationItem id="SF0_4832_1" chargeState="4" experimentalMassToCharge="1007.708591" rank="1" passThreshold="true" calculatedMassToCharge="1007.700997" peptide_ref="Pep5028">
      <PeptideEvidenceRef peptideEvidence_ref="PE5454"/>
      <cvParam accession="MS:1002511" name="cross-link spectrum identification item" cvRef="PSI-MS" value="2301"/>
      <userParam name="Kojak:kojak_score" value="1.010000"/>
      <userParam name="Kojak:delta_score" value="0.345000"/>
      <userParam name="Kojak:ppm_error" value="-7.54E+000"/>
      <userParam name="Kojak:e-value" value="3.738000"/>
      <userParam name="Kojak:ion_match" value="9"/>
      <userParam name="Kojak:consecutive_ion_match" value="1"/>
    </SpectrumIdentificationItem>
    <cvParam accession="MS:1000894" name="retention time" cvRef="PSI-MS" unitAccession="UO:0000010" unitCvRef="UO" unitName="second" value="68.7000"/>
</SpectrumIdentificationResult>
	
	
<PeptideEvidence id="PE5683" dBSequence_ref="DBSeq112" peptide_ref="Pep5238" isDecoy="false" post="?" pre="?">
</PeptideEvidence>
<PeptideEvidence id="PE5684" dBSequence_ref="DBSeq112" peptide_ref="Pep5237" isDecoy="false" post="?" pre="?">
</PeptideEvidence>	

<PeptideEvidence id="PE5617" dBSequence_ref="DBSeq43" peptide_ref="Pep5176" isDecoy="false" post="?" pre="?">
</PeptideEvidence>
<PeptideEvidence id="PE5618" dBSequence_ref="DBSeq43" peptide_ref="Pep5175" isDecoy="false" post="?" pre="?">
</PeptideEvidence>

<PeptideEvidence id="PE5453" dBSequence_ref="DBSeq10" peptide_ref="Pep5027" isDecoy="false" post="?" pre="?">
</PeptideEvidence>
<PeptideEvidence id="PE5454" dBSequence_ref="DBSeq10" peptide_ref="Pep5028" isDecoy="false" post="?" pre="?">
</PeptideEvidence>

  
<Peptide id="Pep5237">
   <PeptideSequence>NNFTYVGNGAHLKYYKDCQYR</PeptideSequence>
   <Modification location="16" monoisotopicMassDelta="138.068074" residues="K">
    <cvParam accession="MS:1002509" name="cross-link donor" cvRef="PSI-MS" value="2301"/>
    <cvParam accession="UNIMOD:1898" name="Xlink:DSS[138]" cvRef="UNIMOD"/>
   </Modification>
   <Modification location="18" monoisotopicMassDelta="57.021464" residues="C">
    <cvParam accession="UNIMOD:4" name="Carbamidomethylation" cvRef="UNIMOD"/>
   </Modification>
</Peptide>
<Peptide id="Pep5238">
   <PeptideSequence>HGIKANGSSM</PeptideSequence>
   <Modification location="4" residues="K">
    <cvParam accession="MS:1002510" name="cross-link acceptor" cvRef="PSI-MS" value="2301"/>
   </Modification>
</Peptide>

<Peptide id="Pep5175">
   <PeptideSequence>LDVPKQSSQR</PeptideSequence>
   <Modification location="5" monoisotopicMassDelta="138.068074" residues="K">
    <cvParam accession="MS:1002509" name="cross-link donor" cvRef="PSI-MS" value="2271"/>
    <cvParam accession="UNIMOD:1898" name="Xlink:DSS[138]" cvRef="UNIMOD"/>
   </Modification>
</Peptide>
<Peptide id="Pep5176">
   <PeptideSequence>FQNLDKK</PeptideSequence>
   <Modification location="6" residues="K">
    <cvParam accession="MS:1002510" name="cross-link acceptor" cvRef="PSI-MS" value="2271"/>
   </Modification>
</Peptide>

<Peptide id="Pep5027">
   <PeptideSequence>CNGPAGTVCLTTFKDVCANR</PeptideSequence>
   <Modification location="14" monoisotopicMassDelta="138.068074" residues="K">
    <cvParam accession="MS:1002509" name="cross-link donor" cvRef="PSI-MS" value="2201"/>
    <cvParam accession="UNIMOD:1898" name="Xlink:DSS[138]" cvRef="UNIMOD"/>
   </Modification>
   <Modification location="1" monoisotopicMassDelta="57.021464" residues="C">
    <cvParam accession="UNIMOD:4" name="Carbamidomethylation" cvRef="UNIMOD"/>
   </Modification>
   <Modification location="9" monoisotopicMassDelta="57.021464" residues="C">
    <cvParam accession="UNIMOD:4" name="Carbamidomethylation" cvRef="UNIMOD"/>
   </Modification>
   <Modification location="17" monoisotopicMassDelta="57.021464" residues="C">
    <cvParam accession="UNIMOD:4" name="Carbamidomethylation" cvRef="UNIMOD"/>
   </Modification>
</Peptide>
<Peptide id="Pep5028">
   <PeptideSequence>NHEEEMKSMQGSSR</PeptideSequence>
   <Modification location="7" residues="K">
    <cvParam accession="MS:1002510" name="cross-link acceptor" cvRef="PSI-MS" value="2201"/>
   </Modification>
</Peptide>

Best regards
Gerhard

**Comment by germa** [comment]
[Hoopmann_ERROR_Report.docx](https://github.com/HUPO-PSI/mzIdentML/files/2083763/Hoopmann_ERROR_Report.docx)

**Comment by colin-combe** [comment]
for what its worth, I also think the file is correct in this respect but get unwarranted errors from v1.4.29 of the validator

@mhoopmann - its missing its start and end values for PeptideEvidences, they're required if not from a de novo search, right? 
(https://github.com/HUPO-PSI/mzIdentML/issues/103)

**Comment by germa** [comment]
Should be solved now by new version mzIdentMLValidator_GUI_v1.4.30-SNAPSHOT.zip

**Comment by colin-combe** [comment]
> Should be solved now by new version mzIdentMLValidator_GUI_v1.4.30-SNAPSHOT.zip

No, I don't think so. 

I think the validator is now passing files where there are 4 SpectrumIdentificationItems containing an MS:1002511 cv param with the same value *within a single SpectrumIdentificationResult*. 

So the validator has just changed from failing valid files to passing invalid files?

**Comment by colin-combe** [comment]
@germa - yeah, sorry, there were some things I was unaware of when i wrote that previous post, see #105

**Comment by germa** [comment]
I think the problem is that there can be not only pairs of SpectrumIdentificationItems (SII's) containing a MS:1002511 CvParam with the same value in the SII's of the same SpectrumIdentificationResult (SIR), for two reasons:

First, if one uses isotope labelled linkers there can occur four SII's with the same value.

Secondly, the SII's can also occur multiple times because of the charge states.

Therefore when you identified the same peptide in n different charge states - as in your example file test2.mzid - then one can have in total 2n SII's (if no isotopically linkers were used) resp. 4n SII's (if isotopically linkers were used) with the same value for the CvParam MS:1002511 (cross-link spectrum identification item).

Unfortunately all these cases are not explicitly considered/distinguished in the spec doc yet, what causes the confusion here, see also
https://github.com/HUPO-PSI/mzIdentML/issues/105 and
https://github.com/Rappsilber-Laboratory/xiSPEC_ms_parser/issues/12

**Comment by colin-combe** [comment]
hi - thanks for reply, I agree that some cross-linking use cases are not fully worked out in the current version of the spec.

I'm now confused about how charge states are dealt with even in the simple case:

> Secondly, the SII's can also occur multiple times because of the charge states.

I don't know, but it looks to me like this isn't the case? Statements in spec doc like "chargeState MUST be identical over both SII elements" imply to me that if charge state was different it would be a different pair of SII elements?

Could you point to something that indicates there can be multiples of two SII's with the same MS:1002511 value and different charge states?

**Comment by colin-combe** [comment]
Hi again,

I'm going to mention some people who might be able to help with the preceding question -  whether the SII pairs (linked by same MS:1002511value) can occur multiple times because of different charge states:

@lutzfischer , @lars-kolbowski, @andrewrobertjones 

Any ideas folks?

@germa, as before, if you can point to something that indicates it works as you say then that would also help resolve this.  

This is more specifically issue #105 but the discussion is happening here,

best wishes,
Colin

**Comment by germa** [comment]
OK, I think you're right: according to the explanation for Feature D in Figure 3 in the spec doc "The ... and chargeState MUST be identical over both SII elements,"
the  MS:1002511 values for different charge states must be indeed different.
So I will change the validator to check this and to allow only 2 resp. 4 (for isotope labelled linkers) SII's with the same value for the MS:1002511 cvParam.

**Comment by germa** [comment]
adapted in version mzIdentMLValidator_GUI_v1.4.32-SNAPSHOT
