### ISSUE TITLE
CV terms for PSM, peptide, protein, protein group and mod localisation - need clean up

### ISSUE THREAD

**Issue by andrewrobertjones** [HUPO-PSI/mzIdentML#25]
Just opening a comment here to remind us we need to do this. In Ghent, we discussed making different CV terms for all of PSM, peptide, protein, protein group and mod localisation so that reading software could easily tell, say under SpectrumIdentificationItem, whether the score is for a PSM, peptide or mod localisation. 

Mod localisation will have to specific terms anyway, since the values have a special structure. Most important work therefore is separating PSM and peptide-level scores, so a reader can figure this out.

I have assigned to @edeutsch since Eric offered to take a look in Ghent, but other helpers would be very welcome!

**Comment by andrewrobertjones** [comment]
ACTION: Gerhard going to make a brief report of the terms we have, and we will create new terms where needed separating PSMs and peptides

**Comment by germa** [comment]
[CV-terms for PTM, PSM, peptide, protein and protein-group scores.docx](https://github.com/HUPO-PSI/mzIdentML/files/272801/CV-terms.for.PTM.PSM.peptide.protein.and.protein-group.scores.docx)

**Comment by germa** [comment]
[CV-terms for PTM, PSM, peptide, protein and protein-group scores.docx](https://github.com/HUPO-PSI/mzIdentML/files/282210/CV-terms.for.PTM.PSM.peptide.protein.and.protein-group.scores.docx)

**Comment by andrewrobertjones** [comment]
Thanks @germa for this.
I added some comments to the document, but there are still a few parts unclear to me. Perhaps we should discuss in detail on our next call

**Comment by andrewrobertjones** [comment]
Proposal from Eric:
[PSI-MS_statisticEntries.xlsx](https://github.com/HUPO-PSI/mzIdentML/files/307250/PSI-MS_statisticEntries.xlsx)

term component definitions:
  - attribute			a general property of an entity (may be a statistic, or a more general property)
  - statistic			a derived numerical metric generally related to confidence in a result
  - PTM localization		related to the exact position of a mass modification (not necessarily a biological PTM)
  - PSM-level			pertaining to one or more peptide-spectrum matches
  - peptide ion-level		pertaining to one or more PSM with the same sequence, modifications, charge
  - modified peptide-level	pertaining to one or more PSMs with the same sequence and modifications
  - peptide sequence-level	pertaining to one or more distinct peptide sequences, irrespective of charge or modification
  - protein-level		pertaining to one or more specific protein entries
  - protein group-level		pertaining to one or more protein ambiguity groups

-----------------------------------------

- analysis attribute

  - PTM localization attribute
    - PTM localization single result statistic
      - PTM localization PSM-level statistic
      - PTM localization distinct peptide-level statistic
    - PTM localization result list statistic

  - identification attribute
    - single identification result attribute
      - PSM-level identification attribute
        - PSM-level identification statistic
          - PSM-level identification confidence metric
            - PSM-level search engine specific statistic
        - cross-linking attribute
        - product ion attribute
      - peptide sequence-level identification attribute
        - peptide sequence-level identification statistic
      - protein-level identification attribute
        - protein-level identification statistic
      - protein group-level identification attribute
        - protein group-level identification statistic
    - result list attribute
      - PSM-level result list attribute
        - PSM-level result list statistic
      - distinct peptide-level result list attribute
        - distinct peptide-level result list statistic
      - protein-level result list attribute
        - protein-level result list statistic
      - protein group-level result list attribute
        - protein group-level result list statistic

**Comment by andrewrobertjones** [comment]
Reviewed current structure, looks good overall.

Andy and Eric will continue to work on this and the mapping file

**Comment by andrewrobertjones** [comment]
I have checked in the Excel file into the CV branch on GitHub but this needs a bit more work. @edeutsch  could you take another look next?

**Comment by edeutsch** [comment]
Okay, I will take control of this file. I have done a little light editing, but my next goal is to get this integrated back into the CV. I am very concerned that this file and the main CV are diverging with every release that Gerhard does, and remerging is going to be painful.

I will need to do some testing first, but then I will contact @germa to synchronize a re-merge.

What shall we do about all the "frag: a ion - H2O" et al. terms. Should we obsolete them? Or just leave them but label like "DEPRECATED: frag: a ion - H2O"?

**Comment by andrewrobertjones** [comment]
I think they already are flagged as deprecated in the term name,  or did we revert that? I would prefer for the definitions to say deprecated instead of term names. Mzid 1.1 exporters could find this irritating otherwise

**Comment by edeutsch** [comment]
Okay, sorry for the delay, but I have re-merged the sheet into the CV. Here's the history as I understand it.

Using my script, I exported all the relevant terms and children that Gerhard listed in his document. This went into the Excel sheet. I took a broad hack at reorganizing everything as described above. Andy then spent some time with it as well. In the mean time, Gerhard has released from new CV versions and we're a bit out of sync, but not terribly so. So, using another script I have remerged the contents of the reorganized spreadsheet into the newest CV file. This may mean that a few terms are a bit out of order, but I propose we do one more round of cleanup after merging.

[psi-ms-new.obo.txt](https://github.com/HUPO-PSI/mzIdentML/files/331276/psi-ms-new.obo.txt)

Gerhard and/or Andy, would you do a diff between this file and the current CV and make sure you're happy with what has been done, and fix anything that seems amiss. would be nice to keep a record of any changes you make.

specific notes:
- there is one term that has an extra digit in the id. It is:
id: MS:10025560
name: DeBunker:score threshold
- Instead of 25560 it should just be 2560. I propose we just surreptitiously fix it rather than keeping it as is or going through the process of obsoleting and such. I doubt this term is used much and if it is, it may well be used with the intended id instead of the type term id. Others may feel differently.

- I (or rather the script) has removed a lot of the multiple parentage. I suggest that this just makes it all more complicated and harder to maintain and understand. The most common case for this is terms that were both in "identification results" and "search-engine specific scores" and such, I propose with the new org, this is not necessary and probably undesirable. If it were somehow better to main a single parent for all search-engine specific things, I would propose that all the intermediate search-engine specific terms could go under a single one.

- There will likely be some significant implications for the mapping file with this merge change. I hope that Gerhard can go in and check all the mapping rules and see if they need to be adjusted.

That's it. What do you think? I hope we can merge these in before any other terms are proposed. As I said, once this is merged, it might be worth going through this once more and making things a little bit tidier.

**Comment by germa** [comment]
I now merged Eric's version psi-ms-new.obo.with the latest changes from our latest version (3.90.3).
The changes are recorded in the 'Changes to new version after merging.txt' file
Since Eric introduced some new terms I had to shift the ID's for the terms MS:1002668 until MS:1002686 to MS:1002688 until MS:1002706

[Changes to new version after merging.txt](https://github.com/HUPO-PSI/mzIdentML/files/336731/Changes.to.new.version.after.merging.txt)
[psi-ms-new.txt](https://github.com/HUPO-PSI/mzIdentML/files/336732/psi-ms-new.txt)

**Comment by germa** [comment]
Here the files again with two further corrections:

[Changes to new version after merging.txt](https://github.com/HUPO-PSI/mzIdentML/files/337083/Changes.to.new.version.after.merging.txt)
[psi-ms-new.txt](https://github.com/HUPO-PSI/mzIdentML/files/337084/psi-ms-new.txt)

**Comment by germa** [comment]
In case you are happy with the new version I can make an official release of both the .obo file and the mapping files from the validator.

**Comment by edeutsch** [comment]
Hi Gerhard, I feel bad because it looks like I have unintentionally created a lot of extra work for you. I thought I was integrating my changes into the latest CV, but it looks like I was using an old one. I don't know how this happened, but it was not my intent.

I'm concerned that you shifted existing released IDs to make room for mine? ooo, it looks that way. So for example, you changed "supplemental collision energy" from 2680 to 2700? I think that this will cause more damage than we want. Some people have probably already started using those terms, so we shouldn't switch them now.

So I guess I would propose that I redo my integration. This is all done by software anyway, so not too hard. But this time I will make sure I am using the latest CV 3.90.3. And I will try to fix the code for some of the things that you noted that it did wrong (like PSI-PI vs PSI:PI).

But then you would need to check my work again and maybe do a few fixes. But it should be 1000x easier than the torture I just put you through.

Is that okay? Shall I redo and send you another proposed revision?

Sorry!
Eric

**Comment by germa** [comment]
Hi Eric, not so dramatic. I corrected the shifted ID's and think it looks ok now.

[Changes to new version after merging.txt](https://github.com/HUPO-PSI/mzIdentML/files/338714/Changes.to.new.version.after.merging.txt)
[psi-ms-new.txt](https://github.com/HUPO-PSI/mzIdentML/files/338715/psi-ms-new.txt)

**Comment by germa** [comment]
Hi Eric, you added the new term

[Term]
id: MS:1002696
name: neutral loss molecule
def: "Fragment ion is modified from its normal m/z due to a spontaneous loss of a the specified neutral molecule formula. This is used in conjuction with another ion type, such as frag: y ion." [PSI:PI]
is_a: MS:1002307 ! fragmentation ion type

Should this replace the old term

[Term]
id: MS:1000336
name: neutral loss
def: "The loss of an uncharged species during a rearrangement process. The value slot holds the molecular formula in Hill notation of the neutral loss molecule, see PMID: 21182243. This term must be used in conjunction with a child of the term MS:1002307 (fragmentation ion type)." [PSI:MS]
xref: value-type:xsd\:string "The allowed value-type for this CV term."
is_a: MS:1001055 ! modification parameters

? If so, we should also define a value slot for  MS:1002696

**Comment by edeutsch** [comment]
The old term 336 is fine. My new proposed term can be discarded.

**Comment by germa** [comment]
The new psi-ms.obo is released now and the mapping files of the mzIdentML validator are adapted.
