### ISSUE TITLE
Validation of PIA examples

### ISSUE THREAD

**Issue by julianu** [HUPO-PSI/mzIdentML#54]
Just asking, because they were left out before I uploaded the new versions:
@edeutsch Are the PIA examples validating for you now? these are MSGFplus_tandem.pia.1.2.mzid.gz and mouse_dataset_-_combination.pia.1.2.mzid.gz in multi_search and teh PIA_... in protein_inference.

**Comment by edeutsch** [comment]
ah, thanks, here's what my CV validator finds:
INFO: Validating file 'PIA_Rosetta_peak_list_2a_+_Ecoli_spectra.mzid'
ERROR: cvParam delta m/z has a value, but it should not!
WARNING: MS:1001062 should be 'Mascot MGF format' instead of 'Mascot MGF file'

INFO: Validating file 'mouse_dataset_-_combination.pia.1.2.mzid'
ERROR: cvParam delta m/z has a value, but it should not!
WARNING: MS:1001062 should be 'Mascot MGF format' instead of 'Mascot MGF file'
WARNING: MS:1001476 should be 'X!Tandem' instead of 'X\!Tandem'
WARNING: MS:1002052 should be 'MS-GF:SpecEValue' instead of 'MS-GF:SpecEValu'

INFO: Validating file 'PIA_Rosetta_peak_list_2a_-_neat.mzid'
WARNING: MS:1001062 should be 'Mascot MGF format' instead of 'Mascot MGF file'
ERROR: cvParam delta m/z has a value, but it should not!

same issues for the other files.

**Comment by julianu** [comment]
I uploaded updates of the files (#55), @edeutsch could you please check again?

**Comment by edeutsch** [comment]
WARNING: MS:1001413 should be 'search tolerance minus value' instead of 'search tolerance minus valu'

rror at file /net/db/projects/PSI/mzIdentML/1.2/genDoc/PIA_Rosetta_peak_list_2a_-_neat.mzid, line 3774, char 71
  Message: Datatype error: Type:InvalidDatatypeValueException, Message:Value 'Rosetta peak list 2a.mgf' is NOT a valid URI .

spaces not permitted.

**Comment by julianu** [comment]
And another new version, hopefully with less typos...

**Comment by julianu** [comment]
Please try to validate again, @edeutsch. I just checked, my last uploads are still valid with the newest validator (1.4.20) by Gerhard,
In the telco you said, it might be possible to also provide us with your validator as well?

**Comment by edeutsch** [comment]
These are all fine now.
Yes, I will see about making this available or doing a daily git pull and post the validation results where everyone can see them.
