### ISSUE TITLE
Exclamation in names in XLMOD.obo

### ISSUE THREAD

**Issue by lutzfischer** [HUPO-PSI/mzIdentML#61]
I just wanted to add a cross-linker to the obo-file and when trying to check it with obo-edit I found, that it ignores everything in the name-field that comes after an exclamation mark.

Currently i had single site cross-linker modification named like 
name: [cross-linker name]![Hydrolyzed|Amidated|...]
e.g.
name: BS3!Hydrolyzed

Only in obo-edit I see instead BS3 now three times - for the cross-linker and for the two modified states that we have in the list.

Seems like in an obo-file "!" starts a comment.

So we either have to escape the exclamation mark or just rename these.
The probably more sensible approach would be to rename these - as this would remove potential errors in future.

How much is the XLMOD already in use and can we still rename a mayor part of the entries?
What would be a good alternative naming scheme?

**Comment by edeutsch** [comment]
I would definitely encourage using a different notation that does not involve exclamation points, as these always need to be escaped in the obo format, which is awkward. If you can just as easily use a different symbol, I suggest that highly!

**Comment by lutzfischer** [comment]
I agree with Eric. I assume the crosslink examples would need to be updated. Any other impact anybody can see for now?

**Comment by germa** [comment]
I think beside noone is already using the XLMOD.obo. Maybe it would be made sende to use a colon instead of the exclamation mark.

**Comment by lutzfischer** [comment]
I used a bit of a structured naming scheme:
Xlink:[Base name]:[label state]!modification

Would using another time colon be god/bad/confusing?

**Comment by edeutsch** [comment]
First, I think all the Xlink: prefixes have been removed from the CV. I
think we agreed that we don’t need a prefix for every term in the CV. So I
think those should be removed.



Second, I don’t think making the name a complex parsable entity is the best
strategy here. It is my opinion that our CV terms should at least aspire
eventually to proper ontologies, and as such should be as natural as
possible. I feel it is best to imagine a journal article or Wikipedia entry
that mentions a concept in natural language and that concept is the name in
the CV and can be hyperlinked. So I suggest instead of:



name: DSS:d4!Amidated



we should use:



name: deuterium-labelled amidated DSS



with no start caps and generally natural English, so that one can write:



After purification, BSA was cross-linked with *deuterium-labelled amidated
DSS* prior to digestion with trypsin.



And the concept as you write it in your methods could be linked to the
concept in the CV.



If some software needs to disentangle this, then I suggest we make this
term multi-parented under:



is_a deuterium-labelled crosslinker

is_a amidated crosslinker



rather than creating a name that software would parse. I think this defeats
the vision of ontologies.



Just my opinion. Others may disagree.









*From:* Lutz Fischer [mailto:notifications@github.com]
*Sent:* Monday, June 27, 2016 9:49 AM
*To:* HUPO-PSI/mzIdentML
*Cc:* Eric Deutsch; Comment
*Subject:* Re: [HUPO-PSI/mzIdentML] Exclamation in names in XLMOD.obo (#61)



I used a bit of a structured naming scheme:
Xlink:[Base name]:[label state]!modification

Would using another time colon be god/bad/confusing?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/HUPO-PSI/mzIdentML/issues/61#issuecomment-228804325>,
or mute the thread
<https://github.com/notifications/unsubscribe/AMHnhrld5_VCcFN-CPu-lsGjLV4OBHPOks5qP_7ygaJpZM4I92fK>
.

**Comment by lutzfischer** [comment]
I like the 
is_a deuterium-labelled crosslinker

possibly with a parent term 
"labelled cross-linker"

is_a amidated cross-linker
We had that discussion before -whether we want to add amidated versions of the cross-linker at all - because it is just one possible way to stop the reaction. And while I am not against having these in XLMOD as such - do we need to flag these up individually?

**Comment by mwalzer** [comment]
:+1: for the is_a notation and keeping hierarchy

**Comment by andrewrobertjones** [comment]
Agreed that @germa will make this change.

**Comment by andrewrobertjones** [comment]
@germa  will also insert intermediate parent terms for this
