### ISSUE TITLE
def: in obo for cross-linker

### ISSUE THREAD

**Issue by lutzfischer** [HUPO-PSI/mzIdentML#62]
I was just adding BDP-NHP and I wanted to add 
"Biotin Aspartate Proline n-hydroxyphthalamide cross-linker"
as the definition.
However for at least some entries we have seemingly IUPAC names as definition.
For DBP-NHP that appears to be:
4-{2-[(5-{[1-(3-carboxy-2-{4-[(1,3-dioxo-2,3-dihydro-1H-isoindol-2-yl)oxy]-4-oxobutanamido}propanoyl)pyrrolidin-2-yl]formamido}-1-({1-[(carboxymethyl)carbamoyl]-5-(5-{2-oxo-hexahydro-1H-thieno[3,4-d]imidazolidin-4-yl}pentanamido)pentyl}carbamoyl)pentyl)carbamoyl]pyrrolidin-1-yl}-3-{4-[(1,3-dioxo-2,3-dihydro-1H-isoindol-2-yl)oxy]-4-oxobutanamido}-4-hydroxybutanoic acid

(got this [here](http://www.chemicalize.org/structure/#!mol=OC%28%3DO%29CNC%28%3DO%29C%28NC%28%3DO%29C%28NC%28%3DO%29C1CCCN1C%28C%28NC%28%3DO%29CCC%28%3DO%29ON1C%28%3DO%29c2c%28C1%3DO%29cccc2%29CC%28%3DO%29O%29O%29CCCCNC%28%3DO%29C1CCCN1C%28%3DO%29C%28NC%28%3DO%29CCC%28%3DO%29ON1C%28%3DO%29c2c%28C1%3DO%29cccc2%29CC%28%3DO%29O%29CCCCNC%28%3DO%29CCCCC1SCC2C1NC%28%3DO%29N2&source=fp))

I can add that in; but is the meaning of that field something that a average human should be able to understand? At least for me this means nothing. 
But it has the advantage that you could actually recreate the structure from that name.

what is the function of the of the def: field?

**Comment by germa** [comment]
I think one should not use the IUPAC names as definition.
If one is puristic one would use the IUPAC name in the name field, "Biotin Aspartate Proline n-hydroxyphthalamide cross-linker" as definition and the the other names and the abbreviation as synonyms.

But in order to make it more readable for humans, I would propose to use the simpler "Biotin Aspartate Proline n-hydroxyphthalamide cross-linker" either as name or as the definition. If you use it as name, then we should add the abbreviations (which are momentarily used as name) as synonym.
If we really need it we can either add the IUPAC name as synonym or add a special property named IUPAC_Name

Unimod.obo and PSI-MOD.obo are also not using the IUPAC names in the name field.

**Comment by andrewrobertjones** [comment]
We agree to follow @germa suggestion, and possibly include external URLs where possible as a reference
